packages:
  - ./java-example/spring-boot/spring-data-jpa-async/web-client
  - ./java-example/spring-boot/webauthn/webauthn-client
allowBuilds:
  sharp: false
  unrs-resolver: false

minimumReleaseAge: 10080 # 7 days in minutes

overrides:
  chokidar: '>=5'
  eslint-import-resolver-typescript: '^4.4.4'
  postcss@<8.5.10: '>=8.5.10'
  semver: '>=7'

trustPolicy: no-downgrade
