packages:
  - ./java-example/spring-boot/spring-data-jpa-async/web-client
  - ./java-example/spring-boot/webauthn/webauthn-client

onlyBuiltDependencies:
  - unrs-resolver

enablePrePostScripts: true
legacyPeerDeps: true
autoInstallPeers: true
strictPeerDependencies: false
overrides:
  "@types/react": ^19.2.2
  "@types/react-dom": ^19.2.2
  eslint@=9.39.0: 9.38.0
  '@eslint/js@=9.39.0': 9.38.0
