server:
  port: ${port:8089}
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8&characterSetResults=UTF-8
    username: root
    password: ""
    tomcat:
      # X-Ray トレースを使う場合は有効化する
      #      jdbc-interceptors: com.amazonaws.xray.sql.mysql.TracingInterceptor
      max-active: 20
      min-idle: 10
      jmx-enabled: true
logging:
  level:
    jdbc: OFF
    jdbc.sqltiming: DEBUG
