#debug: true
server:
  port: ${port:8089}

spring:
  jackson:
    default-property-inclusion: non_null

  datasource:
    tomcat:
      url: "jdbc:h2:mem:actor;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
      driver-class-name: org.h2.Driver
      username: sa
      password:
      max-active: 20
      min-idle: 10

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      database: h2
      transaction-type: RESOURCE_LOCAL
      show-sql: false
      hibernate:
        ddl-auto: update
        show_sql: false
        use_sql_comments: true
        format_sql: true
        enable_lazy_load_no_trans: true

  data:
    jpa:
      repositories:
        enabled: true
  sql:
    init:
      continue-on-error: true
