version: '3.8'
services:
  front:
    image: spring-boot-cassandra:latest
    container_name: java-cassandra-server
    ports:
      - 8080:8080
#    environment:
#      - "SPRING_DATA_CASSANDRA_CONTACT_POINTS=cassandra1"
    depends_on:
      - cassandra1
    networks:
      - java-cassandra-network

  cassandra1:
    image: poad/docker-cassandra:jdk11
    container_name: cassandra1
    environment:
      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
      - "CASSANDRA_DC=datacenter1"
    ulimits:
      memlock: -1
      nproc: 32768
      nofile: 100000
    ports:
      - 7000:7000
      - 7001:7001
      - 9042:9042
      - 9160:9160
    expose:
      - 7000
      - 7001
      - 9042
      - 9160
    networks:
      - java-cassandra-network

  cassandra2:
    image: poad/docker-cassandra:jdk11
    container_name: cassandra2
    environment:
      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
      - "CASSANDRA_DC=datacenter1"
      - "CASSANDRA_SEEDS=cassandra1"
    ulimits:
      memlock: -1
      nproc: 32768
      nofile: 100000
    depends_on:
      - cassandra1
    networks:
      - java-cassandra-network

  cassandra3:
    image: poad/docker-cassandra:jdk11
    container_name: cassandra3
    environment:
      - "CASSANDRA_CLUSTER_NAME=Test Cluster"
      - "CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch"
      - "CASSANDRA_DC=datacenter1"
      - "CASSANDRA_SEEDS=cassandra1"
    ulimits:
      memlock: -1
      nproc: 32768
      nofile: 100000
    depends_on:
      - cassandra1
    networks:
      - java-cassandra-network

networks:
  java-cassandra-network:
