---
micronaut:
  server:
    port: 8080
  application:
    name: micronaut-native
---
datasources:
  default:
    url: jdbc:mysql://127.0.0.1:3306/micronaut
    username: root
    password: ""
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    connectionTimeout: 4000
jpa:
  default:
    packages-to-scan:
      - 'com.github.poad.example.micronaut.entity'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

