version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: test
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql_ddl:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - quarkus-mp-example-network

  frontend:
    build:
      context: ../../../
      dockerfile: src/main/docker/Dockerfile
    container_name: quarkus-mp-example
    environment:
      DB_URL: mysql://mysql:3306/test
    depends_on:
      - mysql
    ports:
      - 8080:8080
    networks:
      - quarkus-mp-example-network


networks:
  quarkus-mp-example-network:
  default:
    external:
      name: quarkus-mp-example-network
