version: '3.8'
services:

  frontend:
    image: dynamo-front
    container_name: dynamo-front
    environment:
      ENV: local
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_KEY: test
      SPRING_PROFILES_ACTIVE: compose
    depends_on:
      - dynamodb
    ports:
      - 8080:8080
    networks:
      - dynamodb-spring-data

  dynamodb:
    image: amazon/dynamodb-local
    command: -jar DynamoDBLocal.jar -inMemory -sharedDb
    container_name: dynamodb
    volumes:
      - "./dynamodb-data:/home/dynamodblocal/data"
    ports:
      - 8000:8000
    networks:
      - dynamodb-spring-data

networks:
  dynamodb-spring-data:
  default:
    external:
      name: dynamodb-spring-data