version: '3.7'
services:
  database:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: webauthn
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./mysql_ddl:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - webauthn-example-network
  backend:
    image: poad/poad/webauthn-rp-example:1.0.0
    container_name: webauthn-api-server
    depends_on:
      - database
    ports:
      - 8080:8080
    networks:
      - webauthn-example-network
networks:
  webauthn-example-network:
  default:
    external:
      name: webauthn-example-network