server:
  port: 8089

spring:
  datasource:
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    properties:
      database: MySQL
      transaction-type: RESOURCE_LOCAL
      show-sql: false
      hibernate: ddl-auto=create-drop

  data:
    jpa:
      repositories:
        enabled: true
