spring:
  application:
    name: "morphological-analyis-kuromoji-api"

logging:
  level:
    root:
      INFO
    com.github.poad.examples.kuromori.service.MorphologicalAnalysisService: TRACE

management:
  endpoints:
    web:
      exposure:
        #        include: "*"
        include: "prometheus"

#  metrics:
#    export:
#      cloudwatch:
#        namespace: KuromojiApi
