server:
  port: ${port:8089}
#debug: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: ""
    tomcat:
#      jdbc-interceptors: com.amazonaws.xray.sql.mysql.TracingInterceptor
      max-active: 20
      min-idle: 10
      jmx-enabled: true
  jpa:
    properties:
      database: MySQL
      transaction-type: RESOURCE_LOCAL
      show-sql: false
      hibernate: ddl-auto=create-drop

  data:
    jpa:
      repositories:
        enabled: true
  sql:
    init:
      continue-on-error: true
