spring:
  application:
    name: App Name
  profiles:
    active: "local"

---
spring:
  profiles: "local"

dynamodb:
  endpoint: "http://localhost:8000"
  region: ap-northeast-1
---
spring:
  profiles: "compose"

dynamodb:
  endpoint: "http://dynamodb:8000"
  region: ap-northeast-1
