CREATE TABLE "USER" (
 "ID" INT NOT NULL AUTO_INCREMENT,
 "NAME" VARCHAR(100) NOT NULL,
 PRIMARY KEY ("ID")
);

CREATE TABLE "MESSAGE" (
 "ID" INT NOT NULL AUTO_INCREMENT,
 "AUTHOR" INT NOT NULL REFERENCES "USER"("ID"),
 "MESSAGE" VARCHAR(100) NOT NULL,
 PRIMARY KEY ("ID")
);
