server:
  port: 8089

spring:
  jackson:
    default-property-inclusion: non_null

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/test?characterEncoding=UTF-8&characterSetResults=UTF-8
    username: root
    password:
    tomcat:
      jmx-enabled: true
      max-active: 20
      min-idle: 10

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      database: MySQL
      transaction-type: RESOURCE_LOCAL
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true
        enable_lazy_load_no_trans: true
