name: Integration

on:
  push:
     branches:
     - main
  pull_request:
    branches:
      - main

  workflow_dispatch: null
jobs:

  android:
    strategy:
      matrix:
        path:
          - android/HelloAndroid

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false

    - name: Set up JDK 21
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        java-version: 21
        distribution: liberica

    - name: Setup cache
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae #v5.0.5
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build with Gradle (${{ matrix.path }})
      working-directory: ${{ matrix.path }}
      run: |
        chmod +x gradlew
        ./gradlew build -x test

  java-example:
    timeout-minutes: 120
    strategy:
      matrix:
        targets:
          - path: java-example
          - path: java-example/spring-boot/morphological-analyis/kuromoji
          - path: java-example/spring-boot/spring-boot-cassandra
          - path: java-example/spring-boot/spring-boot-data-dynamodb
          - path: java-example/spring-boot/spring-boot-data-jpa-example
          - path: java-example/spring-boot/spring-boot-data-jpa-query-example
          - path: java-example/spring-boot/spring-data-jpa-async/spring-data-jpa-async
          - path: java-example/spring-boot/spring-boot-jdbc-example
          - path: java-example/spring-boot/spring-boot-jdbi-example
          - path: java-example/spring-boot/spring-boot-jpa-example
          - path: java-example/spring-boot/spring-boot-metrics
          - path: java-example/spring-boot/spring-boot-micrometer
          - path: java-example/spring-boot/spring-boot-web-example
          - path: java-example/spring-boot/spring-boot-web-thymeleaf-example
          - path: java-example/spring-boot/webauthn/server

    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false
    - name: Set up JDK  25
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
      with:
        java-version: 25
        distribution: liberica

    - name: Setup cache
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae #v5.0.5
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build with Gradle (${{ matrix.targets.path }})
      run: |
        cd ${{ matrix.targets.path }}
        chmod +x gradlew
        ./gradlew build -x test

  node:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        persist-credentials: false

    - name: Use Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: 'lts/*'
        check-latest: true
        package-manager-cache: false

    - uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8
      name: Install pnpm
      with:
        run_install: |
          - recursive: true
            args: [--no-frozen-lockfile]

    - name: build
      run: pnpm all
